env:
  DRY_RUN: false # set to true to disable publishing releases
agents:
  queue: kubernetes

steps:
  - name: ":go: go fmt"
    key: test-go-fmt
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: golang:1.20
                command: .buildkite/steps/test-go-fmt.sh

  - name: ":linux: Linux AMD64 Tests"
    key: test-linux-amd64
    artifact_paths: junit-*.xml
    plugins:
      - kubernetes:
          podSpec:
            nodeSelector:
              role: workers
            containers:
              - image: golang:1.20
                command: .buildkite/steps/tests.sh
      - test-collector#v1.2.0:
          files: "junit-*.xml"
          format: "junit"

  - name: ":linux: Linux ARM64 Tests"
    key: test-linux-arm64
    command: ".buildkite/steps/tests.sh"
    artifact_paths: junit-*.xml
    agents:
      queue: agent-runners-linux-arm64
    plugins:
      - kubernetes:
          podSpec:
            nodeSelector:
              role: workers
            containers:
              - image: golang:1.20
                command: .buildkite/steps/tests.sh
      - test-collector#v1.2.0:
          files: "junit-*.xml"
          format: "junit"

  - name: ":satellite: Detect Data Races"
    key: test-race-linux
    artifact_paths: junit-*.xml
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: golang:1.20
                command: .buildkite/steps/tests.sh -race
      - test-collector#v1.2.0:
          files: "junit-*.xml"
          format: "junit"
